easy_admin:
    site_name: 'Maintenance informatique'
    show:
        max_results: 20
    design:
        brand_color: 'rgba(26, 188, 156, 0.85)'
        assets:
            css:
            js:
            #favicon: '/assets/backend/favicon.png'
        menu:
            - {label: 'Application'}
            - {entity: 'Editor', icon: 'home', params: {}}
            - {entity: 'Software', params: {}}
            - {entity: 'Versioning', params: {}}
            - {label: 'Objets'}
            - {entity: 'Computer', params: {}}
            - {label: 'Utilisateurs'}
            - {entity: 'User', icon: 'user', params: {}}
    list:
        actions:
            - {name: 'edit', icon: 'pencil', label: false, title: 'Edit'}
            - {name: 'delete', icon: 'remove', label: false, title: 'Delete'}
    formats:
        date:     'd/m/Y'
        time:     'H:i'
        datetime: 'd/m/Y H:i:s'
        number: '%.2f'
    entities:
        # List the entity class name you want to manage
        #Event:
            #class: App\Entity\Site\Event
            #label: 'Evénement'
            #help: 'Gestion des événements'
            #list:
                #title: 'Liste des événements'
            #form:
                #title: 'Ajout événement'
                #form_options: { validation_groups: ['Default'] }
                #fields:
                    #- id
                    #- {property: 'libelle', icon: 'customer'}
                    #- {property: 'type', icon: 'customer'}
                    #- {property: 'agence', icon: 'customer'}
                    #- {property: 'resume', type: 'fos_ckeditor'}
                    #- {property: 'description', type: 'fos_ckeditor'}
                    #- {property: 'start', icon: 'customer'}
                    #- {property: 'end', icon: 'customer'}
                    #- {property: 'images', icon: 'customer', type: 'App\Form\Objet\IllustrationType', type_options: { by_reference: false }}
                    #- {property: 'cascades', icon: 'customer', type: 'App\Form\Site\CascadeType', type_options: { by_reference: false }}
            #new:
                #help: 'Evénements : ajout'
                #form_options: { validation_groups: ['Default', 'Event'] }
                #fields:
                    #- '-id'
            #edit:
                #help: 'Evénements : modification'
                #title: 'Edit événement'
                #fields:
                    #- '-id'
        Computer:
            class: App\Entity\Admin\Computer
            label: 'Machines'
            list:
                title: "Liste des Ordinateurs"
            form:
                title: 'Ajout de machine'
                form_options: { validation_groups: ['Default'] }
                fields:
                    - {type: 'tab', columns: 6, label: 'Information de base'}
                    - id
                    - {property: 'libelle', label: 'nom de la machine', icon: 'customer'}
                    - {property: 'ip', label: 'IP de la machine', icon: 'customer'}
                    - {property: 'type', label: 'nom de la machine', icon: 'customer'}
                    - {property: 'os', icon: 'customer'}
                    - {property: 'environnement', icon: 'customer'}
                    - {type: 'tab', label: 'Logiciels installés'}
                    - {property: 'softwares', label: 'logiciels', icon: 'customer', type: 'easyadmin_autocomplete', type_options: { class: 'App\Entity\Application\Software' }}
                    #- {property: 'presentation', type: 'fos_ckeditor'}
                    #- {property: 'evenements', type: 'easyadmin_autocomplete'}
            new:
                help: 'Ordinateur : ajout'
                form_options: { validation_groups: ['Default', 'Event'] }
                fields:
                    - '-id'
            edit:
                help: 'Ordinateur : modification'
                title: 'Edit ordianteur'
                fields:
                    - '-id'
        Editor:
            class: App\Entity\Application\Editor
            label: 'Editeurs'
            list:
                title: 'Liste des éditeurs'
            form:
                title: "Ajout d'un éditeur"
                form_options: { validation_groups: ['Default'] }
                fields:
                    - {type: 'tab', columns: 2, label: 'Informations de base'}
                    - id
                    - {property: 'libelle', label: 'libellé', icon: 'customer'}
                    - {property: 'description', label: 'description', icon: 'customer'}
                    - {property: 'chapo', label: 'résumé', icon: 'customer'}
                    - {type: 'tab', label: 'Logiciels associés'}
                    - {property: 'softwares', label: 'Logiciels', icon: 'customer', type: 'easyadmin_autocomplete', type_options: { class: 'App\Entity\Application\Software' }}
            new:
                help: 'Editeur : ajout'
                form_options: { validation_groups: ['Default'] }
                fields:
                    - '-id'
            edit:
                help: 'Editeur : modification'
                title: 'Edit Editeur'
                fields:
                    - '-id'
        Software:
            class: App\Entity\Application\Software
            label: 'Logiciels'
            list:
                title: 'Liste des logiciels'
                actions:
                    - { name: 'admin_versioning_commit', type: 'route', icon: 'plus-square', label: false }
            form:
                title: "Ajout d'un logciel"
                form_options: { validation_groups: ['Default'] }
                fields:
                    - {type: 'tab', columns: 2, label: 'Informations de base'}
                    - id
                    - {property: 'libelle', label: 'libellé', icon: 'customer'}
                    - {type: 'tab', label: 'Editeurs associés'}
                    - {property: 'editor', label: 'Editeurs', icon: 'customer', type: 'easyadmin_autocomplete', type_options: { class: 'App\Entity\Application\Editor' }}
                    - {type: 'tab', label: 'Ordinateurs associés'}
                    - {property: 'machines', label: 'Ordinateurs', icon: 'customer', type: 'easyadmin_autocomplete', type_options: { class: 'App\Entity\Admin\Computer' }}
            new:
                help: 'Editeur : ajout'
                form_options: { validation_groups: ['Default'] }
                fields:
                    - '-id'
            edit:
                help: 'Editeur : modification'
                title: 'Edit Editeur'
                fields:
                    - '-id'
        Versioning:
            class: App\Entity\Admin\Versioning
            label: 'Gestionnaire de version'
            list:
                title: 'Liste des logiciels gérés'
            form:
                title: "Ajout d'un repository"
                form_options: { validation_groups: ['Default'] }
                fields:
                    - {type: 'section', label: 'Informations de base'}
                    - id
                    - {property: 'repository', icon: 'customer'}
                    - {property: 'username', icon: 'customer'}
                    - {property: 'password', icon: 'customer'}
                    - {type: 'section', label: 'Logiciel associé'}
                    - {property: 'users', label: 'Utilisateurs', icon: 'customer', type: 'easyadmin_autocomplete', type_options: { class: 'App\Entity\Admin\User' }}
            new:
                help: 'Versioning : ajout'
                form_options: { validation_groups: ['Default'] }
                fields:
                    - '-id'
            edit:
                help: 'Versioning : modification'
                title: 'Edit Versioning'
                fields:
                    - '-id'
        User:
            class: App\Entity\Admin\User
            label: 'Utilisateurs'
            list:
                title: 'Liste des utilisateurs'
            form:
                fields:
                    - username
                    - email
                    - enabled
                    - lastLogin
                    # if administrators are allowed to edit users' passwords and roles, add this:
                    - { property: 'plainPassword', type: 'text', type_options: { required: false } }
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'Agent': 'ROLE_USER', 'Administrateur': 'ROLE_ADMIN' } } }
            edit:
                form_options: { validation_groups: ['Profile'] }
            new:
                fields:
                    - { property: 'plainPassword', type_options: { required: true} }
                form_options: { validation_groups: ['Registration'] }
        #Menu:
            #class: App\Entity\Objet\Menu
            #label: 'Entrés de menu'
            #list:
                #title: 'Liste des menus'
            #form:
                #fields:
                    #- libelle
                    #- lien
                    #- { property: 'categorie', type: 'choice', type_options: { multiple: false, choices: { 'Principale': 'main', 'Secondaire': 'second' } } }
                    #- { property: 'type', type: 'choice', type_options: { multiple: false, choices: { 'Lien': 'lien', 'Libelle': 'libelle' } } }
                    #- rang
            #edit:
                #form_options: { validation_groups: ['Default'] }
            #new:
                #form_options: { validation_groups: ['Default'] }